version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install the latest version of Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python3 -
      - run:
          name: Run isort
          command: |
            isort --check-only --diff .
      - run:
          name: Run black
          command: |
            black --check --diff .
      - run:
          name: Run tests
          command: |
            pytest --doctest-modules
