version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install the latest version of Poetry
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_UNINSTALL=1 python -
            curl -sSL https://install.python-poetry.org | python3 -
      - run:
          name: Install dependencies
          command: |
            poetry install
      - run:
          name: Run isort
          command: |
            isort --check-only --diff .
      - run:
          name: Run black
          command: |
            black --check --diff .
      - run:
          name: Run tests
          command: |
            python -m doctest data_warehouse_utils/utils.py
            python -m doctest data_warehouse_utils/helpers.py
            python -m doctest data_warehouse_utils/gcs_helper_functions.py
