version: 2.1
# try again

orbs:
  poetry: talkiq/poetry@4.0.0

jobs:
  build:
    executor:
      name: python/default
      tag: "3.9"
    steps:
      - checkout
      - poetry/install
      - run:
          command: pytest --doctest-modules

workflows:
  build-and-test:
    jobs:
      - build
