version: 2.1

orbs:
  poetry: talkiq/poetry@4.0.0

jobs:
  build:
    executor: python@3.9
    steps:
      - checkout
      - poetry/install
      - run:
          command: pytest --doctest-modules

workflows:
  build-and-test:
    jobs:
      - build
