version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            poetry install -vvv
            cat /home/circleci/.cache/pypoetry/virtualenvs/*/log/activate.log
      - run:
          name: Run isort
          command: |
            isort --check-only --diff .
      - run:
          name: Run black
          command: |
            black --check --diff .
      - run:
          name: Run tests
          command: |
            pytest --doctest-modules
