version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pytest==5.2 isort==5.12.0 black==23.1.0
      - run:
          name: Run isort
          command: |
            isort --check-only --diff .
      - run:
          name: Run black
          command: |
            black --check --diff .
      - run:
          name: Run tests
          command: |
            pytest --doctest-modules
